- README.md
- src/Database.hs
- src/Main.hs
Handle initialization of db table internally, without relying on nft-server to do so
> Add db table initialization

- .github/local-formatting.sh
- README.md
- config.toml
- flake.nix
- ogmios-datum-cache.cabal
- src/Api.hs
- src/Api/Handler.hs
- src/Api/Types.hs
- src/Api/WebSocket.hs
- src/Api/WebSocket/Json.hs
- src/Api/WebSocket/Types.hs
- src/App/Env.hs
- src/Block/Fetch.hs
- src/Block/Types.hs
- src/Config.hs
- src/Database.hs
- src/Main.hs
- Add possibility to change filter in control API
- Add API endpoint to lookup currently processed block (Close #21)
- Add config option to start block fetcher from lastly processed block (Close #21)
- Add config option to auto-start block fetcher (Close #20)
- Change config schema for block fetcher to make sense with these changes (described in README)
> Rework block fetcher

- .github/local-formatting.sh
- fourmolu.yaml
- src/Api.hs
- src/Api/Error.hs
- src/Api/Handler.hs
- src/Api/Types.hs
- src/Api/WebSocket.hs
- src/Api/WebSocket/Json.hs
- src/Api/WebSocket/Types.hs
- src/App.hs
- src/App/Env.hs
- src/Block/Fetch.hs
- src/Block/Filter.hs
- src/Block/Types.hs
- src/Config.hs
- src/Database.hs
- src/Main.hs
- src/PlutusData.hs
> Formatting & styleguide

- src/Block/Fetch.hs
Close #34 
Another mutex is always a solution for concurrency issue.
> Don't start block fetcher if it's already running

- README.md
- src/Api.hs
- src/Api/Handler.hs
- src/Api/WebSocket.hs
- src/Api/WebSocket/Json.hs
- src/Api/WebSocket/Types.hs
> Add healthcheck endpoints

- ogmios-datum-cache.cabal
- src/Api/Handler.hs
- src/Api/Types.hs
- src/Api/WebSocket.hs
- src/Api/WebSocket/Types.hs
- src/Block/Filter.hs
> Make datum fitler optional in API

- src/Config.hs
- src/Main.hs
> Fix default datum filter in config

- Makefile
Copies mostly from other projects but with our config settings.
> Makefile init

- src/Parameters.hs
- test/Spec/Parameters.hs
The solution is to remove `show`
> Fix double quoting in dbConnection string

- README.md
- src/Api/Types.hs
- src/Api/WebSocket.hs
- src/Api/WebSocket/Types.hs
- src/App.hs
- src/Block/Fetch.hs
- src/Block/Types.hs
- src/Parameters.hs
- test/Spec/Api/WebSocket/Types.hs
- test/Spec/Parameters.hs
Close #39 
Tested on seabug, also added parser for Byron blocks for better logging (will be replaced by more general block in #64)
> Add support to start from origin

- README.md
- Replace CancelFetchBlocks by SetDatumFilter
- Do we actually need `GetHealthCheck` method in WebSocket?
> Fix some issues in README.md

- src/Api/WebSocket.hs
> return a Fault response in case of bad request

- ogmios-datum-cache.cabal
- src/Api/Handler.hs
- src/Api/WebSocket/Json.hs
- src/Block/Fetch.hs
- src/Block/Filter.hs
- src/Block/Types.hs
- src/Block/Types/Alonzo.hs
- src/Block/Types/Babbage.hs
- src/Block/Types/Byron.hs
- src/Database.hs
Using one block type was a mistake, so I've split them back. Also closes #100
> Split block types

- CHANGELOG.md
- README.md
- src/App.hs
- src/Block/Fetch.hs
- src/Block/Types.hs
- src/Parameters.hs
Also rename `--origin` to `--from-origin` (better name)
Close #104
> Add flag to start from tip

- src/Database.hs
Replay of https://github.com/mlabs-haskell/ogmios-datum-cache/pull/117
Fixes https://github.com/Plutonomicon/cardano-transaction-lib/issues/804
This PR fixes an issue when `GetTxByHash` fails to return a transaction if there are duplicates of it in the database. The reason for the duplication is presumably because the same block is processed twice after the node switches to a new fork and sends a `RollBackward` message to the consumer.
> Add primary key to transactions table, Remove tx duplicates on init

- CHANGELOG.md
- src/Api.hs
- src/Api/Handler.hs
- src/Api/WebSocket/Json.hs
- src/Block/Fetch.hs
- src/Block/Types.hs
- src/Block/Types/Alonzo.hs
- src/Block/Types/Babbage.hs
- src/DataHash.hs
- src/Database.hs
- test/Spec/Block/Alonzo.hs
- test/Spec/Block/Babbage.hs
- test/Spec/Block/Examples/RollForward_Alonzo.json
- test/Spec/Block/Examples/RollForward_Babbage.json
- test/Spec/Block/Parsers.hs
> Cache raw TXs

- src/Database.hs
I'm also modifying the behavior of insertion for transactions for the same reasons as #118
> Update the database if we get the same datum again

- README.md
> Add support channel information

- CHANGELOG.md
- README.md
- src/Api/WebSocket.hs
- src/Api/WebSocket/Json.hs
- src/Database.hs
> Change the error handling in `getDatumsByHashes`

- ogmios-datum-cache.cabal
> Add -threaded to GHC options
